apiVersion: v1
kind: Service
metadata:
  name: echoserver-svc
  namespace: echoserver
  labels:
    app: echoserver
    tier: frontend
spec:
  type: NodePort
  selector:
    app: echoserver
    tier: frontend
  ports:
    - port: 80
      nodePort: 30002
  